version: '3'
services:
  pokemon-api:
    image: dottjt/pokemon-api
    container_name: 'pokemon-api'
    ports:
      - 2000:2000
      - 2001:2001
    build:
      context: .

    # networks:
    #   - docker-network
    # depends_on:
    #   - pokemon-api-postgres

  # pokemon-api-postgres:
  #   image: postgres:alpine
  #   container_name: 'pokemon-api-postgres'
  #   ports:
  #     - 5432:2345
  #   volumes:
  #     - ./pokemon-api-postgres:/var/lib/postgresql/data:rw
  #   restart: always
  #   env_file:
  #     - .env

# networks:
#   docker-network:
#     driver: bridge
